### ISSUE TITLE
2D marker locations

### ISSUE THREAD

**Issue by semihgunel** [jessedmarshall/CAPTURE_demo#1]
Hi,
Thanks a lot for the great project, the results look really interesting!
I was wondering if 2D marker locations for each camera are available or not, possibly with the corresponding image data. I can only find 3D poses inside the published data.
Best,
Semih

**Comment by jessedmarshall** [comment]
Hey Semih,

Good to hear from you and I enjoyed the DeepFly3D paper. This dataset doesn't have the 2D views, but we are releasing one of images and 3D data soon, likely after the holidays. Hopefully that works and I'll be in touch.
Best,
Jesse

**Comment by semihgunel** [comment]
Hi Jesse,
Thanks for the kind words!
To be clear, sometime after the holidays, you are planning to upload **one of** the 12 camera images + 3d data, right (without the 2d marker locations)?
Best,
Semih

**Comment by jessedmarshall** [comment]
So the dataset is one of RGB video cameras and 3D keypoints, with calibration information, so it will have the reprojections.
